### ISSUE TITLE
Support for passing initial coefficient starting values (initial estimates/guesses)

### ISSUE THREAD

**Issue by tomwenseleers** [pbreheny/ncvreg#12]
I have a problem where I already have initial coefficient estimates obtained using nnls, or where I fit multichannel longitudinal models and where the coefficients for a next time slice are known a priori to be very similar to those of the previous time slice. Would there by an performance advantage in these cases of being able to pass these coefficients as initial coefficient starting values perhaps (i.e. using a warm start)?

**Comment by pbreheny** [comment]
`ncvreg` is organized around the idea of fitting a regularization *path*, not just obtaining a fit for a single value of &lambda;.  The idea of supplying initial values doesn't really make sense in this framework, since the initial values would just come from the previous values of &lambda;.

Now, I do agree that there are many cases where it would be useful to have a separate function that lets you fit a model at a single value of &lambda; and supply an initial value.  This function does not currently exist in `ncvreg`, but it isn't because I don't think it's valuable -- I just haven't had the time to implement it.  Maybe this summer?  But I can't make any promises.

**Comment by pbreheny** [comment]
This is now implemented in the function `ncvfit()`, available in ncvreg > 3.12.
