### ISSUE TITLE
Could an intercept option be added?

### ISSUE THREAD

**Issue by commintern** [pbreheny/ncvreg#6]
Hi Patrick,

I would like to use SCAD method provided by `ncvreg` to analyze some data. The model involves no intercept term. However, unlike `glmnet` that users can choose not to inlcude intercept terms, it seems that `ncvreg` includes an intercept in the model automatically.  Hence, I fail to analyze my data by `ncvreg`. Could no intercept option be included in the function `ncvreg`. Thanks in advance.

**Comment by pbreheny** [comment]
This is unlikely to be available any time soon.  Generally speaking, I try to add useful options to `ncvreg` when feasible, but in this case, it is just so difficult (at least for me) to imagine any scenario in which this would matter, let alone make sense.  For example, consider linear regression.  Here's the analysis with and without an intercept:

```r
X <- scale(matrix(rnorm(50*5), 50, 5), scale=FALSE)
y <- rnorm(50)
library(glmnet)
coef(glmnet(X, y), s=0.01)[-1]
# 0.03654258  0.14570818  0.07929119  0.28725708 -0.22337889
coef(glmnet(X, y, intercept=FALSE), s=0.01)[-1]
# 0.03654258  0.14570818  0.07929119  0.28725708 -0.22337889
```

In other words, we get the *exact* same result.  Now, in logistic regression, etc., it won't be *exactly* the same, but still, it's hard for me to imagine a scenario in which this is an important difference.  I'm not trying to be dismissive, it's just that this seems to me like an option that would only be useful in a one-in-a-million scenario, so I'm not particularly inclined to spend time implementing it when there are other, more important things to do.

**Comment by suolisuoli** [comment]
Thanks for constructing the packages. However, I think options to exclude the intercept are somewhat necessary. Since anyone can add a column of all 1s to the original design matrix to fit the intercept manually, it will hurt nothing if the default coding does not include the intercept. On the other hand, coding with mandatory intercept will be problematic if someone must exclude the intercept. E.g. I am doing sparse SVD and it can be reformulated as a regression problem with penalization but without intercept. I cannot use the code because I must exclude the intercept.

**Comment by pbreheny** [comment]
Won't you get the exact same result regardless of whether you include an intercept or not?

**Comment by suolisuoli** [comment]
No. Because we only reformulate our problem to a penalized regression problem with some specific design matrix, the original problem is not a regression. The "residual" also cannot have a common mean in our case. Honestly, I feel frustrated that I found it cannot be applied to our problem with only a little bit difference. But anyway, thanks for your effort on the packages and your reply.

**Comment by pbreheny** [comment]
Well, my point is that they give the exact same result either way (see above demonstration), so whether the option exists or not is irrelevant.

However, if you have some sort of non-standard optimization that falls outside of what `ncvreg()` allows, there is also the `ncvfit()` function which just gives you direct access to the optimization function and you set up all the standardization/intercept/etc exactly how you want them. Sounds like this would be the right function for you?

**Comment by suolisuoli** [comment]
Yes! I think ncvfit() can work pretty well on this scenario.

In fact I came from https://github.com/pbreheny/grpreg/issues/30. I was looking for ways that can remove intercept including in grpreg() by default. I read your apply to mynanshan.
 
We are trying to use the group SCAD or MCP penalty. Now I understand that ncvfit() can fit any penalized regression problem with or without intercept, even with different weights on each variable. But do we have a similar function in grpreg package that can solve penalized regression problems with grouped covariates, like grpfit(), comparable to ncvfit().

**Comment by pbreheny** [comment]
Unfortunately, there is not currently such a function in **grpreg**. I agree that there should be, I just haven't had time to implement one.
